spring.application.name=ms-beautique-query
server.port=8084
server.servlet.context-path=/ms-beautique-query

spring.mongodb.database=ms-beautique-query
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.username=ms-sync
spring.mongodb.password=ms-sync